[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "viscalc"
version = "0.1.0"
description = "A modular and beginner-friendly Python calculator package"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
    {name = "Bhargav Sai Viswanath Adhimulam"}
]
keywords = ["calculator", "math", "learning", "education"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Education",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Education",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/AdhimulamBhargavSaiViswanath-05/viscalc"
Repository = "https://github.com/AdhimulamBhargavSaiViswanath-05/viscalc"
"Bug Tracker" = "https://github.com/AdhimulamBhargavSaiViswanath-05/viscalc/issues"

[project.optional-dependencies]
dev = [
    "pytest>=9.0",
    "build>=1.0",
    "twine>=5.0"
]

[tool.setuptools.packages.find]
where = ["src"]
